### ISSUE TITLE
【Solved】subprocess.CalledProcessError: Command '['git', 'describe']' returned non-zero exit status 128.

### ISSUE THREAD

**Issue by huchi00057** [huchi00057/YOLOV7#1]
```
  Traceback (most recent call last):
　　  File "D:\desktop\yolov7\detect.py", line 184, in <module>
　　  detect()
　　  File "D:\desktop\yolov7\detect.py", line 34, in detect
　　  model = attempt_load(weights, map_location=device) # load FP32 model
　　  File "D:\desktop\yolov7\model\experimental.py", line 87, in attempt_load
　　  attempt_download(w)
　　  File "D:\desktop\yolov7\utils\google_utils.py", line 30, in attempt_download
　　  tag = subprocess.check_output('git tag' , shell=True).decode().split()[-1]
　　  File "D:\anaconda\lib\subprocess.py", line 424, in check_output
　　  return run(*pepenargs, stdout=PIPE, timeout=timeout, check=True,
         File "D:\anaconda\lib\subprocess.py", line 528 in run
         raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'describe']'returned non-zero exit status 128.
```
![image](https://user-images.githubusercontent.com/46515944/179228147-afa620db-29d7-4267-9a90-47b330ace9e2.png)

**Comment by huchi00057** [comment]
【Solution】
Follow the path mentioned in command to find **subprocess.py**
![image](https://user-images.githubusercontent.com/46515944/179229394-a1e5b5e1-5097-4761-9a38-576d7762dc94.png)

**Ctrl + F**to find return run(*popenargs
![image](https://user-images.githubusercontent.com/46515944/179229934-52e22624-e0d9-463b-a1ec-12ac6763501d.png)

chagne "check = True" to be "False".

![image](https://user-images.githubusercontent.com/46515944/179229700-d876bdb9-5a73-4348-be58-072f4a7c22ac.png)

**Comment by huchi00057** [comment]
Reference：

- https://blog.csdn.net/weixin_41649031/article/details/112978028

- https://blog.csdn.net/weixin_44457768/article/details/107756536?ops_request_misc=&request_id=&biz_id=102&utm_term=subprocess.CalledProcessError:&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduweb~default-0-107756536.first_rank_v2_pc_rank_v29&spm=1018.2226.3001.4187
